export const COLORS = {
    PRIMARY_COLOR : "#2C0735",
    SECONDARY_COLOR : "#5E4AE3",
    TERCIARY_COLOR : "#6DD3CE",
    NEUTRAL_COLOR : "#1E1E1E",
    BLACK_COLOR : "#000",
    WHITE_COLOR : "#FFF",
    ERROR_COLOR : "#BF0101",
    WARNING_COLOR : "#FFA600",
    SUCCESS_COLOR : "#28A30F",
    BACKGROUND_COLOR : "#E8DFEA"
};