export const COLORS = {
    PRIMARY_COLOR : "#6E5CE5",
    SECONDARY_COLOR : "#5E4AE3",
    TERCIARY_COLOR : "#21005D",
    QUATERNARY_COLOR: "#6750A4",
    NEUTRAL_COLOR : "#1E1E1E",
    BLACK_COLOR : "#000",
    WHITE_COLOR : "#FFF",
    ERROR_COLOR : "#BF0101",
    WARNING_COLOR : "#FFA600",
    SUCCESS_COLOR : "#28A30F",
    BACKGROUND_COLOR: "#E8DFEA",
    ANOTHERBACK_COLOR: "#F5EFF7",
    CARD_COLOR: "#E8E5FB",
    SECBACKGROUND_COLOR: "#A697D1",
    PREMIUM_COLOR: "#2C0735"
};